import { createDramaDetailEpisodeListBindings } from './dramaDetailEpisodeListBindings.js'
import { createDramaDetailResourceLibraryBindings } from './dramaDetailResourceLibraryBindings.js'
import { createDramaDetailResourceDialogBindings } from './dramaDetailResourceDialogBindings.js'

/**
 * 把剧集详情页已有的列表、资源库和弹窗状态装配成可 v-bind 的属性袋。
 * 不创建新状态，也不改自动保存或离开保护。
 */
export function createDramaDetailPageBindings(values = {}) {
  const episodeListBindings = createDramaDetailEpisodeListBindings({
    addingEpisode: values.addingEpisode,
    deletingEpisodeId: values.deletingEpisodeId,
    dramaId: values.dramaId,
    episodeEmptyState: values.episodeEmptyState,
    episodes: values.episodes,
    epStatusLabel: values.epStatusLabel,
    handleReadinessAction: values.handleReadinessAction,
    nextEpisodeNumber: values.nextEpisodeNumber,
    onAddEpisode: values.onAddEpisode,
    onBatchImportEpisodes: values.onBatchImportEpisodes,
    onDeleteEpisode: values.onDeleteEpisode,
    openEpisodeBatchImport: values.openEpisodeBatchImport,
    withProjectListReturnTo: values.withProjectListReturnTo,
  })

  const resourceLibraryBindings = createDramaDetailResourceLibraryBindings({
    activeResTab: values.activeResTab,
    addingEpisode: values.addingEpisode,
    assetImageUrl: values.assetImageUrl,
    characterRoleLabel: values.characterRoleLabel,
    charError: values.charError,
    charKw: values.charKw,
    charList: values.charList,
    charLoading: values.charLoading,
    charPage: values.charPage,
    charPageSize: values.charPageSize,
    charTotal: values.charTotal,
    currentEpisodeId: values.currentEpisodeId,
    deleteChar: values.deleteChar,
    deleteProp: values.deleteProp,
    deleteScene: values.deleteScene,
    drama: values.drama,
    goCreateOrAddEpisode: values.goCreateOrAddEpisode,
    loadCharList: values.loadCharList,
    loadPropList: values.loadPropList,
    loadSceneList: values.loadSceneList,
    onCharKwInput: values.onCharKwInput,
    onPropKwInput: values.onPropKwInput,
    onResourceTabKeydown: values.onResourceTabKeydown,
    onSceneKwInput: values.onSceneKwInput,
    openEditChar: values.openEditChar,
    openEditDramaChar: values.openEditDramaChar,
    openEditDramaProp: values.openEditDramaProp,
    openEditDramaScene: values.openEditDramaScene,
    openEditProp: values.openEditProp,
    openEditScene: values.openEditScene,
    openImport: values.openImport,
    openPreview: values.openPreview,
    propError: values.propError,
    propKw: values.propKw,
    propList: values.propList,
    propLoading: values.propLoading,
    propPage: values.propPage,
    propPageSize: values.propPageSize,
    propTotal: values.propTotal,
    propTypeLabel: values.propTypeLabel,
    sceneError: values.sceneError,
    sceneKw: values.sceneKw,
    sceneList: values.sceneList,
    sceneLoading: values.sceneLoading,
    scenePage: values.scenePage,
    scenePageSize: values.scenePageSize,
    sceneTotal: values.sceneTotal,
  })

  const resourceDialogsBindings = createDramaDetailResourceDialogBindings({
    addingEpisode: values.addingEpisode,
    currentEpisodeId: values.currentEpisodeId,
    editCharForm: values.editCharForm,
    editCharSaving: values.editCharSaving,
    editCharVisible: values.editCharVisible,
    editDramaCharForm: values.editDramaCharForm,
    editDramaCharSaving: values.editDramaCharSaving,
    editDramaCharVisible: values.editDramaCharVisible,
    editDramaPropForm: values.editDramaPropForm,
    editDramaPropSaving: values.editDramaPropSaving,
    editDramaPropVisible: values.editDramaPropVisible,
    editDramaSceneForm: values.editDramaSceneForm,
    editDramaSceneSaving: values.editDramaSceneSaving,
    editDramaSceneVisible: values.editDramaSceneVisible,
    editPropForm: values.editPropForm,
    editPropSaving: values.editPropSaving,
    editPropVisible: values.editPropVisible,
    editSceneForm: values.editSceneForm,
    editSceneSaving: values.editSceneSaving,
    editSceneVisible: values.editSceneVisible,
    importError: values.importError,
    importKw: values.importKw,
    importList: values.importList,
    importLoading: values.importLoading,
    importPage: values.importPage,
    importPageSize: values.importPageSize,
    importTotal: values.importTotal,
    importType: values.importType,
    importVisible: values.importVisible,
    importingId: values.importingId,
    assetImageUrl: values.assetImageUrl,
    characterLibraryAPI: values.characterLibraryAPI,
    doGenerateLibImg: values.doGenerateLibImg,
    doImport: values.doImport,
    doUploadLibImg: values.doUploadLibImg,
    generateDramaCharImg: values.generateDramaCharImg,
    generateDramaPropImg: values.generateDramaPropImg,
    generateDramaSceneImg: values.generateDramaSceneImg,
    goCreateOrAddEpisode: values.goCreateOrAddEpisode,
    loadCharList: values.loadCharList,
    loadImportList: values.loadImportList,
    loadPropList: values.loadPropList,
    loadSceneList: values.loadSceneList,
    onImportKwInput: values.onImportKwInput,
    openPreview: values.openPreview,
    previewUrl: values.previewUrl,
    propLibraryAPI: values.propLibraryAPI,
    requestResourceEditorClose: values.requestResourceEditorClose,
    saveChar: values.saveChar,
    saveDramaChar: values.saveDramaChar,
    saveDramaProp: values.saveDramaProp,
    saveDramaScene: values.saveDramaScene,
    saveProp: values.saveProp,
    saveScene: values.saveScene,
    sceneLibraryAPI: values.sceneLibraryAPI,
    uploadDramaCharImg: values.uploadDramaCharImg,
    uploadDramaPropImg: values.uploadDramaPropImg,
    uploadDramaSceneImg: values.uploadDramaSceneImg,
  })

  return {
    episodeListBindings,
    resourceLibraryBindings,
    resourceDialogsBindings,
  }
}
