function nowIso() {
  return new Date().toISOString();
}

function parseJson(value, fallback = null) {
  if (value == null || value === '') return fallback;
  if (typeof value === 'object') return value;
  try {
    return JSON.parse(value);
  } catch (_) {
    return fallback;
  }
}

function toJson(value) {
  return JSON.stringify(value == null ? {} : value);
}

function buildIdentityAnchors(row, referenceAsset) {
  const existing = parseJson(row.identity_anchors, null);
  return {
    ...(existing && typeof existing === 'object' ? existing : {}),
    locked_name: row.name,
    role: row.role || '',
    appearance: row.appearance || row.description || '',
    reference_asset: referenceAsset || '',
    consistency_rule: 'Keep name, face, silhouette, palette, and costume continuity unless a stage override applies.',
    source: 'character_continuity_service',
  };
}

function buildStages(row, episodeRange, referenceAsset) {
  const existing = parseJson(row.stages, null);
  const stages = Array.isArray(existing) && existing.length ? existing : [{
    version: 'v1',
    episode_range: episodeRange,
    appearance: row.appearance || row.description || `${row.name} baseline appearance`,
    reference_asset: referenceAsset || '',
    continuity_note: 'Baseline stage generated by local novel2anime asset bible.',
  }];
  return stages.map((stage) => ({ ...stage, reference_asset: referenceAsset || '' }));
}

function ensureCharacterContinuity(db, log, dramaId, options = {}) {
  const episodes = db.prepare(
    `SELECT episode_number
       FROM episodes
      WHERE drama_id = ? AND deleted_at IS NULL
      ORDER BY episode_number ASC`
  ).all(Number(dramaId));
  const firstEpisode = Number(episodes[0]?.episode_number) || 1;
  const lastEpisode = Number(episodes[episodes.length - 1]?.episode_number) || firstEpisode;
  const episodeRange = [firstEpisode, lastEpisode];
  const rows = db.prepare(
    `SELECT *
       FROM characters
      WHERE drama_id = ? AND deleted_at IS NULL
      ORDER BY sort_order ASC, id ASC`
  ).all(Number(dramaId));
  const now = nowIso();
  let updated = 0;
  const snapshots = [];

  for (const row of rows) {
    const candidate = row.local_path || row.image_url || row.four_view_image_url || '';
    const usableCandidate = /^(?:mock|placeholder):\/\//i.test(String(candidate)) ? '' : candidate;
    const referenceAsset = usableCandidate || (options.allow_mock_fallback === false
      ? ''
      : `mock://dramas/${dramaId}/characters/${row.id}/reference.png`);
    const identityAnchors = buildIdentityAnchors(row, referenceAsset);
    const stages = buildStages(row, episodeRange, referenceAsset);
    db.prepare(
      `UPDATE characters
          SET identity_anchors = ?,
              stages = ?,
              image_url = COALESCE(NULLIF(image_url, ''), ?),
              local_path = COALESCE(NULLIF(local_path, ''), ?),
              updated_at = ?
        WHERE id = ?`
    ).run(toJson(identityAnchors), toJson(stages), referenceAsset, referenceAsset, now, row.id);
    updated += 1;
    snapshots.push({
      character_id: row.id,
      name: row.name,
      identity_anchors: identityAnchors,
      stages,
      reference_asset: referenceAsset,
    });
  }

  log?.info?.('Character continuity snapshots refreshed', {
    drama_id: dramaId,
    character_count: rows.length,
    updated,
  });
  return {
    drama_id: Number(dramaId),
    character_count: rows.length,
    updated,
    episode_range: episodeRange,
    snapshots,
  };
}

module.exports = {
  ensureCharacterContinuity,
};
