'use strict';

const LEGACY_FORMAT_VERSION = 1;
const FORMAT_VERSION = 2;
const SUPPORTED_FORMAT_VERSIONS = Object.freeze([LEGACY_FORMAT_VERSION, FORMAT_VERSION]);
const MINIMUM_ZIP_ARCHIVE_BYTES = 22;

module.exports = Object.freeze({
  FORMAT_VERSION,
  LEGACY_FORMAT_VERSION,
  MINIMUM_ZIP_ARCHIVE_BYTES,
  SUPPORTED_FORMAT_VERSIONS,
});
