import { computed } from 'vue'

import {
  FILM_CREATE_RESOURCE_DIALOG_MODEL_KEYS,
  FILM_CREATE_STORYBOARD_DIALOG_MODEL_KEYS,
} from '../../utils/filmCreateTemplateBindings.js'

/**
 * 把制作页已有状态按工作台分区装配成绑定源。
 * 只搬家，不创建新状态，不改空剧本门闩和离开保护。
 */
export function createFilmCreateWorkspaceBindingSources(ctx = {}) {
  const {
    store, props, scriptWorkbenchMode, storyInput,
    storyStyle, storyType, storyEpisodeCount, scriptTitle,
    scriptContent, showSelectScriptDialog, selectPreviewEpisodeId, isStoryGenRunning,
    dramaId, hasAnyEpisode, scriptGenerating, currentEpisodeId,
    scriptDraftStatus, scriptDraftStatusLabel, selectScriptLoading, selectScriptImporting,
    selectableScriptDramas, selectScriptDramas, saveProjectSettings, showNovelImport,
    router, onGenerateStory, onAddEpisode, onGenerateScript,
    openSelectScriptDialog, loadSelectScriptList, onPickScriptFromDialog, returnToScriptCreation,
    resourcePanelCollapsed, charactersBlockCollapsed, propsBlockCollapsed, scenesBlockCollapsed,
    propUseQuadGrid, sceneUseQuadGrid, characters, scenes,
    characterGenerationDisabledReason, projectActionDisabledReason, propsExtractionDisabledReason, scenesExtractionDisabledReason,
    storyboardMediaActionReason, charactersGenerating, propsExtracting, scenesExtracting,
    generatingCharIds, generatingPropIds, generatingSceneIds, generatingPanoramaIds,
    uploadingResourceId, addingCharToLibraryId, addingCharToMaterialId, addingPropToLibraryId,
    addingPropToMaterialId, addingSceneToLibraryId, addingSceneToMaterialId, regenSbImagesForAsset,
    regenSbImagesProgress, sd2CertifyingId, sd2VoiceUploadingId, hasAssetImage,
    assetImageUrl, charRoleLabel, localPathToUrl, parseExtraImages,
    getCharAffectedStoryboards, getPropAffectedStoryboards, getSceneAffectedStoryboards, sd2ActionLabel,
    sd2VoiceActionLabel, onSelectEpisode, onGenerateCharacters, openAddCharacter,
    showCharLibrary, onExtractProps, showAddProp, showPropLibrary,
    onExtractScenes, openAddScene, showSceneLibrary, onGenerateCharacterImage,
    onGeneratePropImage, onGenerateSceneImage, onGenerateScenePanorama, editCharacter,
    editProp, editScene, onDeleteCharacter, onDeleteProp,
    onDeleteScene, onAddCharacterToLibrary, onAddCharacterToMaterialLibrary, onAddPropToLibrary,
    onAddPropToMaterialLibrary, onAddSceneToLibrary, onAddSceneToMaterialLibrary, onRegenAffectedSbImages,
    doUploadResourceImage, onSetPrimaryImage, onRemoveExtraImage, openImagePreview,
    scrollToStoryboard, onSd2PrimaryAction, onSd2VoicePrimaryAction, onSd2VoiceReplace,
    playSd2Voice, storyboardCount, videoDuration, gridMode,
    storyboardUseFirstLastFrame, storyboardUniversalOmni, storyboardIncludeNarration, lastFrameUseFirstLayoutLock,
    videoFrameContiguity, sbTruncatedDismissed, batchImageStopping, batchVideoStopping,
    dragOverSbId, storyboards, sbSceneId, sbNarration,
    sbUniversalSegmentText, batchImageErrors, batchVideoErrors, batchImageProgress,
    batchVideoProgress, generatingSbImageIds, generatingSbFirstImageIds, generatingSbLastImageIds,
    generatingUniversalSegmentIds, linkingTailFrameIds, usingPrevTailAsFirstIds, ttsSbIds,
    ttsSbNarrationIds, upscalingSbIds, universalOmniPolishProgress, storyboardGenerating,
    universalOmniPolishRunning, exportingStoryboardSheet, batchImageRunning, batchVideoRunning,
    sbTruncatedWarning, uploadingSbImageId, uploadingSbImageSlot, storyboardActionDisabledReason,
    episodeActionDisabledReason, batchActionDisabledReason, batchVideoActionDisabledReason, videoCapabilityReason,
    scriptEstimateStoryboardHint, scriptEstimateStoryboardTitle, scriptEstimateVideoDurationHint, scriptEstimateVideoDurationTitle,
    assetVideoUrl, canUsePrevTailAsFirst, charactersAvailableToAddToSb, getMovementLabel,
    getNextStoryboard, getSbCharacterIds, getSbFirstImage, getSbImage,
    getSbLastImage, getSbLocalImage, getSbPropIds, getSbSelectedCharacters,
    getSbSelectedProps, getSbSelectedScene, getSbFreeReferenceItems, getSbGridImages,
    getSbUniversalOmniRefSlots, getSbVideo, getSbVideoError, getSbVideoReferenceGrid,
    getStripItems, getVideoStripItems, hasSbDraftImagePlaceholder, hasSbFirstLastPair,
    hasSbImage, historyImageLabel, isSbUniversalMode, isSbVideoGenerating,
    onAddSingleStoryboard, onDeleteSingleStoryboard, onExportNarrationSrt, onExportStoryboardSheet,
    onGenerateSbFrameImage, onGenerateSbFramePair, onGenerateSbImage, onGenerateSbVideo,
    onGenerateStoryboard, onInsertStoryboardBefore, storyboardsAPI, storyboardReorderBusy,
    dropTargetStoryboardIndex, onMoveStoryboardUp, onMoveStoryboardDown, onReorderDragStart,
    onReorderDragOver, onReorderDragEnd, onReorderDrop, onLastFrameLayoutLockChange,
    onLinkTailFrameToNext, onOpenSbPromptDialog, onOpenVideoParamsDialog, onPromoteSbFreeReferenceImage,
    onRemoveSbFreeReferenceImage, onRemoveSbHistoryImage, onSaveSbNarrationField, onSaveUniversalSegmentField,
    onSbAddCharacterCommand, onSbImageDragLeave, onSbImageDragOver, onSbImageDrop,
    onSelectSbMainVideo, onSelectStripItem, onStoryboardSceneChange, onStoryboardUseFirstLastFrameChange,
    onStripItemClick, onToggleSbUniversalMode, onTtsSbDialogue, onTtsSbNarration,
    onUniversalSegmentPromptMenu, onUploadSbImageClick, onUpscaleSbImage, onUsePrevTailAsFirst,
    openAiConfig, openGlobalMediaPicker, playSbDialogueTts, playSbNarrationTts,
    sbCanSubmitVideo, sbDialogueAudioRelPath, sbMainVideoPlayerKey, sbNarrationAudioRelPath,
    sbUniversalSegmentTrimmed, sbVideoGenerationDisabledReason, setSbCharacterIds, setSbPropIds,
    showSbFramePromptPreview, startBatchImageGeneration, startBatchVideoGeneration, storyboardImageUrl,
    stripItemTitle, ttsGenerationDisabledReason, doUploadSbImage, showCharSd2Cert,
    showEditCharLibrary, showEditCharacter, showEditProp, showEditPropLibrary,
    showEditScene, showEditSceneLibrary, charLibraryKeyword, charLibraryPage,
    charLibraryPageSize, charLibraryTab, dramaAllCharKeyword, dramaAllCharPage,
    dramaAllCharPageSize, dramaAllPropKeyword, dramaAllPropPage, dramaAllPropPageSize,
    dramaAllSceneKeyword, dramaAllScenePage, dramaAllScenePageSize, propLibraryKeyword,
    propLibraryPage, propLibraryPageSize, propLibraryTab, sceneLibraryKeyword,
    sceneLibraryPage, sceneLibraryPageSize, sceneLibraryTab, addCharRefImage,
    addPropAddRefImage, addPropForm, addPropRefImage, addSceneRefImage,
    editCharLibraryForm, editPropLibraryForm, editSceneLibraryForm, addPropSaving,
    charLibraryList, charLibraryLoading, charLibraryTotal, charSd2CertPayload,
    dramaAllCharList, dramaAllCharLoading, dramaAllCharTotal, dramaAllPropList,
    dramaAllPropLoading, dramaAllPropTotal, dramaAllSceneList, dramaAllSceneLoading,
    dramaAllSceneTotal, editCharLibrarySaving, editCharacterForm, editCharacterPromptGenerating,
    editCharacterSaving, editPropForm, editPropLibrarySaving, editPropPromptGenerating,
    editPropSaving, editSceneForm, editSceneLibrarySaving, editScenePromptGenerating,
    editSceneSaving, extractingAnchors, extractingCharAppearance, extractingPropAddDesc,
    extractingPropDesc, extractingSceneDesc, propLibraryList, propLibraryLoading,
    propLibraryTotal, sceneLibraryList, sceneLibraryLoading, sceneLibraryTotal,
    clearCharRefImage, clearPropRefImage, clearSceneRefImage, debouncedLoadCharLibrary,
    debouncedLoadDramaAllCharList, debouncedLoadDramaAllPropList, debouncedLoadDramaAllSceneList, debouncedLoadPropLibrary,
    debouncedLoadSceneLibrary, doExtractCharFromImage, doExtractFromRef, doExtractFromRef2,
    doExtractPropFromImage, doExtractSceneFromImage, doGenerateCharacterPrompt, doGeneratePropPrompt,
    doGenerateScenePrompt, doGenerateSceneSinglePrompt, extractIdentityAnchors, isCharAddToEpisodeLoading,
    isPropAddToEpisodeLoading, isSceneAddToEpisodeLoading, loadCharLibraryList, loadDramaAllCharList,
    loadDramaAllPropList, loadDramaAllSceneList, loadPropLibraryList, loadSceneLibraryList,
    onAddCharFromLibrary, onAddDramaCharToEpisode, onAddDramaPropToEpisode, onAddDramaSceneToEpisode,
    onAddPropFromLibrary, onAddSceneFromLibrary, onCharLibraryDialogOpen, onCharLibraryTabChange,
    onCloseCharDialog, onClosePropDialog, onCloseSceneDialog, onDeleteCharLibrary,
    onDeletePropLibrary, onDeleteSceneLibrary, onPropLibraryDialogOpen, onPropLibraryTabChange,
    onRefImageDrop, onRefImageDrop2, onRefImageFileChange, onRefImageFileChange2,
    onSceneLibraryDialogOpen, onSceneLibraryTabChange, openEditCharLibrary, openEditPropLibrary,
    openEditSceneLibrary, returnToCharacterPanel, returnToPropPanel, returnToScenePanel,
    submitAddProp, submitEditCharLibrary, submitEditCharacter, submitEditProp,
    submitEditPropLibrary, submitEditScene, submitEditSceneLibrary, showSbPromptDialog,
    showFramePromptEditor, showVideoParamsDialog, editingFramePromptText, sbPromptImageText,
    sbPromptPolishedText, sbPromptVideoText, sbPromptTarget, editingFramePromptRegenerating,
    editingFramePromptSaving, editingFramePromptSb, editingFramePromptSlot, regeneratingLayoutSbIds,
    sbAction, sbAngleH, sbAngleS, sbAngleV,
    sbAtmosphere, sbCreationMode, sbDialogue, sbDof,
    sbDuration, sbLayoutDescription, sbLighting, sbLocation,
    sbMovement, sbPromptPolishing, sbPromptSaving, sbResult,
    sbShotType, sbTime, sbTitle, sbVideoReferenceImageId,
    splitByAudioLoading, videoParamsSaving, videoParamsTarget, angleToPromptFragment,
    canSplitSbByAudio, onPolishSbPrompt, onRegenerateLayoutDescription, onSaveSbPromptDialog,
    onSaveVideoParams, onSplitSbByAudio, onVideoParamsDialogClosed, regenerateEditingFramePrompt,
    saveEditingFramePrompt, setSbCreationModeId,
  } = ctx

  return {
    resourceDialogModelKeys: FILM_CREATE_RESOURCE_DIALOG_MODEL_KEYS,
    storyboardDialogModelKeys: FILM_CREATE_STORYBOARD_DIALOG_MODEL_KEYS,
    scriptWorkbench: {
    scriptWorkbenchMode, storyInput, storyStyle, storyType, storyEpisodeCount,
    scriptTitle, scriptContent, showSelectScriptDialog, selectPreviewEpisodeId,
    isStoryGenRunning, dramaId, hasAnyEpisode, scriptGenerating, currentEpisodeId,
    episodes: computed(() => store.drama?.episodes || []),
    scriptDraftStatus, scriptDraftStatusLabel, selectScriptLoading, selectScriptImporting,
    selectableScriptDramas, selectScriptDramas, saveProjectSettings, showNovelImport,
    router, onGenerateStory, onAddEpisode, onGenerateScript, openSelectScriptDialog,
    loadSelectScriptList, onPickScriptFromDialog, returnToScriptCreation,
  },
    resourcePanel: {
    resourcePanelCollapsed, charactersBlockCollapsed, propsBlockCollapsed, scenesBlockCollapsed,
    propUseQuadGrid, sceneUseQuadGrid, characters, propItems: props, scenes,
    characterGenerationDisabledReason, projectActionDisabledReason, propsExtractionDisabledReason,
    scenesExtractionDisabledReason, storyboardMediaActionReason, charactersGenerating,
    propsExtracting, scenesExtracting, generatingCharIds, generatingPropIds, generatingSceneIds, generatingPanoramaIds,
    uploadingResourceId, addingCharToLibraryId, addingCharToMaterialId, addingPropToLibraryId,
    addingPropToMaterialId, addingSceneToLibraryId, addingSceneToMaterialId, regenSbImagesForAsset,
    regenSbImagesProgress, sd2CertifyingId, sd2VoiceUploadingId, hasAssetImage, assetImageUrl,
    charRoleLabel, localPathToUrl, parseExtraImages, getCharAffectedStoryboards,
    getPropAffectedStoryboards, getSceneAffectedStoryboards, sd2ActionLabel, sd2VoiceActionLabel,
    hasAnyEpisode, onAddEpisode, onSelectEpisode, onGenerateCharacters, openAddCharacter, showCharLibrary, onExtractProps, showAddProp,
    showPropLibrary, onExtractScenes, openAddScene, showSceneLibrary, onGenerateCharacterImage,
    onGeneratePropImage, onGenerateSceneImage, onGenerateScenePanorama, editCharacter, editProp, editScene,
    onDeleteCharacter, onDeleteProp, onDeleteScene, onAddCharacterToLibrary,
    onAddCharacterToMaterialLibrary, onAddPropToLibrary, onAddPropToMaterialLibrary,
    onAddSceneToLibrary, onAddSceneToMaterialLibrary, onRegenAffectedSbImages, doUploadResourceImage,
    onSetPrimaryImage, onRemoveExtraImage, openImagePreview, scrollToStoryboard,
    onSd2PrimaryAction, onSd2VoicePrimaryAction, onSd2VoiceReplace, playSd2Voice,
  },
    storyboardPanel: {
    storyboardCount, videoDuration, gridMode, storyboardUseFirstLastFrame, storyboardUniversalOmni,
    storyboardIncludeNarration, lastFrameUseFirstLayoutLock, videoFrameContiguity, sbTruncatedDismissed,
    batchImageStopping, batchVideoStopping, dragOverSbId, storyboards, characters, scenes, sbSceneId,
    sbNarration, sbUniversalSegmentText, batchImageErrors, batchVideoErrors, batchImageProgress,
    batchVideoProgress, generatingSbImageIds, generatingSbFirstImageIds, generatingSbLastImageIds,
    generatingUniversalSegmentIds, linkingTailFrameIds, usingPrevTailAsFirstIds, ttsSbIds,
    ttsSbNarrationIds, upscalingSbIds, universalOmniPolishProgress, hasAnyEpisode, currentEpisodeId,
    storyboardGenerating, universalOmniPolishRunning, exportingStoryboardSheet, batchImageRunning,
    batchVideoRunning, sbTruncatedWarning, uploadingSbImageId, uploadingSbImageSlot,
    storyboardActionDisabledReason, episodeActionDisabledReason, batchActionDisabledReason,
    batchVideoActionDisabledReason, storyboardMediaActionReason, videoCapabilityReason, scriptEstimateStoryboardHint,
    scriptEstimateStoryboardTitle, scriptEstimateVideoDurationHint, scriptEstimateVideoDurationTitle,
    propItems: props, assetImageUrl, assetVideoUrl, canUsePrevTailAsFirst, charactersAvailableToAddToSb,
    getMovementLabel, getNextStoryboard, getSbCharacterIds, getSbFirstImage, getSbImage, getSbLastImage,
    getSbLocalImage, getSbPropIds, getSbSelectedCharacters, getSbSelectedProps, getSbSelectedScene,
    getSbFreeReferenceItems, getSbGridImages, getSbUniversalOmniRefSlots, getSbVideo, getSbVideoError, getSbVideoReferenceGrid, getStripItems, getVideoStripItems,
    hasAssetImage, hasSbDraftImagePlaceholder, hasSbFirstLastPair, hasSbImage, historyImageLabel,
    isSbUniversalMode, isSbVideoGenerating, onAddEpisode, onAddSingleStoryboard, onDeleteSingleStoryboard,
    onExportNarrationSrt, onExportStoryboardSheet, onGenerateSbFrameImage, onGenerateSbFramePair,
    onGenerateSbImage, onGenerateSbVideo, onGenerateStoryboard, onInsertStoryboardBefore, storyboardsAPI, storyboardReorderBusy, dropTargetStoryboardIndex, onMoveStoryboardUp, onMoveStoryboardDown, onReorderDragStart, onReorderDragOver, onReorderDragEnd, onReorderDrop,
    onLastFrameLayoutLockChange, onLinkTailFrameToNext, onOpenSbPromptDialog, onOpenVideoParamsDialog, onPromoteSbFreeReferenceImage, onRemoveSbFreeReferenceImage,
    onRemoveSbHistoryImage, onSaveSbNarrationField, onSaveUniversalSegmentField, onSbAddCharacterCommand,
    onSbImageDragLeave, onSbImageDragOver, onSbImageDrop, onSelectSbMainVideo, onSelectStripItem,
    onStoryboardSceneChange, onStoryboardUseFirstLastFrameChange, onStripItemClick, onToggleSbUniversalMode,
    onTtsSbDialogue, onTtsSbNarration, onUniversalSegmentPromptMenu, onUploadSbImageClick, onUpscaleSbImage,
    onUsePrevTailAsFirst, openAiConfig, openGlobalMediaPicker, openImagePreview, playSbDialogueTts, playSbNarrationTts,
    sbCanSubmitVideo, sbDialogueAudioRelPath, sbMainVideoPlayerKey, sbNarrationAudioRelPath,
    sbUniversalSegmentTrimmed, sbVideoGenerationDisabledReason, setSbCharacterIds, setSbPropIds,
    showSbFramePromptPreview, startBatchImageGeneration, startBatchVideoGeneration, storyboardImageUrl,
    stripItemTitle, ttsGenerationDisabledReason, saveProjectSettings, doUploadSbImage,
  },
    resourceDialogs: {
    showAddProp, showCharLibrary, showCharSd2Cert, showEditCharLibrary,
    showEditCharacter, showEditProp, showEditPropLibrary, showEditScene,
    showEditSceneLibrary, showPropLibrary, showSceneLibrary, charLibraryKeyword,
    charLibraryPage, charLibraryPageSize, charLibraryTab, dramaAllCharKeyword,
    dramaAllCharPage, dramaAllCharPageSize, dramaAllPropKeyword, dramaAllPropPage,
    dramaAllPropPageSize, dramaAllSceneKeyword, dramaAllScenePage, dramaAllScenePageSize,
    propLibraryKeyword, propLibraryPage, propLibraryPageSize, propLibraryTab,
    sceneLibraryKeyword, sceneLibraryPage, sceneLibraryPageSize, sceneLibraryTab,
    addCharRefImage, addPropAddRefImage, addPropForm, addPropRefImage,
    addSceneRefImage, editCharLibraryForm, editPropLibraryForm, editSceneLibraryForm,
    addPropSaving, charLibraryList, charLibraryLoading, charLibraryTotal,
    charSd2CertPayload, currentEpisodeId, dramaAllCharList, dramaAllCharLoading,
    dramaAllCharTotal, dramaAllPropList, dramaAllPropLoading, dramaAllPropTotal,
    dramaAllSceneList, dramaAllSceneLoading, dramaAllSceneTotal, editCharLibrarySaving,
    editCharacterForm, editCharacterPromptGenerating, editCharacterSaving, editPropForm,
    editPropLibrarySaving, editPropPromptGenerating, editPropSaving, editSceneForm,
    editSceneLibrarySaving, editScenePromptGenerating, editSceneSaving, extractingAnchors,
    extractingCharAppearance, extractingPropAddDesc, extractingPropDesc, extractingSceneDesc,
    propLibraryList, propLibraryLoading, propLibraryTotal, sceneLibraryList,
    sceneLibraryLoading, sceneLibraryTotal, assetImageUrl, charRoleLabel,
    clearCharRefImage, clearPropRefImage, clearSceneRefImage, debouncedLoadCharLibrary,
    debouncedLoadDramaAllCharList, debouncedLoadDramaAllPropList, debouncedLoadDramaAllSceneList, debouncedLoadPropLibrary,
    debouncedLoadSceneLibrary, doExtractCharFromImage, doExtractFromRef, doExtractFromRef2,
    doExtractPropFromImage, doExtractSceneFromImage, doGenerateCharacterPrompt, doGeneratePropPrompt,
    doGenerateScenePrompt, doGenerateSceneSinglePrompt, extractIdentityAnchors, isCharAddToEpisodeLoading,
    isPropAddToEpisodeLoading, isSceneAddToEpisodeLoading, loadCharLibraryList, loadDramaAllCharList,
    loadDramaAllPropList, loadDramaAllSceneList, loadPropLibraryList, loadSceneLibraryList,
    onAddCharFromLibrary, onAddDramaCharToEpisode, onAddDramaPropToEpisode, onAddDramaSceneToEpisode,
    onAddPropFromLibrary, onAddSceneFromLibrary, onCharLibraryDialogOpen, onCharLibraryTabChange,
    onCloseCharDialog, onClosePropDialog, onCloseSceneDialog, onDeleteCharLibrary,
    onDeletePropLibrary, onDeleteSceneLibrary, onPropLibraryDialogOpen, onPropLibraryTabChange,
    onRefImageDrop, onRefImageDrop2, onRefImageFileChange, onRefImageFileChange2,
    onSceneLibraryDialogOpen, onSceneLibraryTabChange, openEditCharLibrary, openEditPropLibrary,
    openEditSceneLibrary, openImagePreview, returnToCharacterPanel, returnToPropPanel, returnToScenePanel, submitAddProp,
    submitEditCharLibrary, submitEditCharacter, submitEditProp, submitEditPropLibrary,
    submitEditScene, submitEditSceneLibrary,
  },
    storyboardDialogs: {
    showSbPromptDialog, showFramePromptEditor, showVideoParamsDialog, editingFramePromptText,
    sbPromptImageText, sbPromptPolishedText, sbPromptVideoText, sbPromptTarget,
    editingFramePromptRegenerating, editingFramePromptSaving, editingFramePromptSb, editingFramePromptSlot,
    regeneratingLayoutSbIds, sbAction, sbAngleH, sbAngleS,
    sbAngleV, sbAtmosphere, sbCreationMode, sbDialogue,
    sbDof, sbDuration, sbLayoutDescription, sbLighting,
    sbLocation, sbMovement, sbNarration, sbPromptPolishing,
    sbPromptSaving, sbResult, sbShotType, sbTime,
    sbTitle, sbVideoReferenceImageId, splitByAudioLoading, videoParamsSaving,
    videoParamsTarget, angleToPromptFragment, assetImageUrl, canSplitSbByAudio,
    getSbFreeReferenceItems, getSbGridImages, onPolishSbPrompt, onPromoteSbFreeReferenceImage,
    onRegenerateLayoutDescription, onRemoveSbFreeReferenceImage, onSaveSbPromptDialog, onSaveVideoParams,
    onSplitSbByAudio, onVideoParamsDialogClosed, openGlobalMediaPicker, openImagePreview,
    regenerateEditingFramePrompt, saveEditingFramePrompt, setSbCreationModeId,
  },
  }
}
