import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { compileScript, parse } from '@vue/compiler-sfc'

const panel = readFileSync(new URL('../src/components/filmCreate/FilmCreateResourcePanel.vue', import.meta.url), 'utf8')

function emptyBlock(marker) {
  const start = panel.indexOf(marker)
  assert.ok(start >= 0, `缺少 ${marker}`)
  const relativeEnd = panel.slice(start).search(/<\/div>\r?\n\s*<\/div>/)
  assert.ok(relativeEnd > 0, `${marker} 空状态未闭合`)
  return panel.slice(start, start + relativeEnd)
}

test('角色空状态提供提取/添加，无剧集时指向创建或选择剧集', () => {
  const block = emptyBlock('v-if="characters.length === 0"')
  assert.match(block, /class="empty-tip resource-empty-tip"/)
  assert.match(block, /role="status"/)
  assert.match(block, /暂无角色，可用「剧本自动提取角色」或「添加角色」/)
  assert.match(block, /v-if="needsEpisode"/)
  assert.match(block, /v-if="!hasAnyEpisode"[\s\S]*goCreateEpisode/)
  assert.match(block, /v-else[\s\S]*goSelectEpisode/)
  assert.match(block, /aria-label="去创建剧集"/)
  assert.match(block, /aria-label="去选择剧集"/)
  assert.match(block, /:aria-label="extractCharactersEmptyAriaLabel"/)
  assert.match(block, /emit\('generate-characters'\)/)
  assert.match(block, /:aria-label="addCharacterEmptyAriaLabel"/)
  assert.match(block, /emit\('add-character'\)/)
  assert.match(block, /:reason="characterGenerationDisabledReason"/)
  assert.match(block, /:reason="projectActionDisabledReason"/)
})

test('道具空状态提供提取/添加，无剧集时指向创建或选择剧集', () => {
  const block = emptyBlock('v-if="propItems.length === 0"')
  assert.match(block, /class="empty-tip resource-empty-tip"/)
  assert.match(block, /暂无道具，可用「从剧本提取道具」或「添加道具」/)
  assert.match(block, /v-if="!hasAnyEpisode"[\s\S]*aria-label="去创建剧集"/)
  assert.match(block, /v-else[\s\S]*aria-label="去选择剧集"/)
  assert.match(block, /:aria-label="extractPropsEmptyAriaLabel"/)
  assert.match(block, /emit\('extract-props'\)/)
  assert.match(block, /:aria-label="addPropEmptyAriaLabel"/)
  assert.match(block, /emit\('add-prop'\)/)
  assert.match(block, /:reason="propsExtractionDisabledReason"/)
})

test('场景空状态提供提取/添加，无剧集时指向创建或选择剧集', () => {
  const block = emptyBlock('v-if="scenes.length === 0"')
  assert.match(block, /class="empty-tip resource-empty-tip"/)
  assert.match(block, /暂无场景，可用「从剧本提取场景」或「添加场景」/)
  assert.match(block, /v-if="!hasAnyEpisode"[\s\S]*aria-label="去创建剧集"/)
  assert.match(block, /v-else[\s\S]*aria-label="去选择剧集"/)
  assert.match(block, /:aria-label="extractScenesEmptyAriaLabel"/)
  assert.match(block, /emit\('extract-scenes'\)/)
  assert.match(block, /:aria-label="addSceneEmptyAriaLabel"/)
  assert.match(block, /emit\('add-scene'\)/)
  assert.match(block, /:reason="scenesExtractionDisabledReason"/)
})

test('无剧集空状态走制作页 onAddEpisode / add-episode，不再点页头或静默滚走', () => {
  assert.match(panel, /const EPISODE_REQUIRED_REASON = '请先创建或选择剧集'/)
  assert.match(panel, /onAddEpisode: \{ type: Function/)
  assert.match(panel, /'add-episode'/)
  assert.match(panel, /function goCreateEpisode\(/)
  assert.match(panel, /props\.onAddEpisode\(\)/)
  assert.match(panel, /emit\('add-episode'\)/)
  const createFnStart = panel.indexOf('function goCreateEpisode')
  const createFnEnd = panel.indexOf('function goSelectEpisode')
  assert.ok(createFnStart >= 0 && createFnEnd > createFnStart)
  const createFn = panel.slice(createFnStart, createFnEnd)
  assert.match(createFn, /props\.onAddEpisode\(\)/)
  assert.match(createFn, /emit\('add-episode'\)/)
  assert.doesNotMatch(createFn, /activateExistingControl/)
  assert.doesNotMatch(createFn, /scrollToScriptAnchor/)
  assert.doesNotMatch(createFn, /header-add-episode/)
  assert.doesNotMatch(panel, /activateExistingControl\('\.header-add-episode'\)/)
  assert.doesNotMatch(panel, /activateExistingControl\('\[aria-label="添加一集"\]'\)/)
  assert.match(panel, /function goSelectEpisode\(/)
  assert.match(panel, /hasAnyEpisode: \{ type: Boolean/)
  assert.match(panel, /onSelectEpisode: \{ type: Function/)
  assert.match(panel, /'select-episode'/)
  const selectFnStart = panel.indexOf('function goSelectEpisode')
  const selectFnEnd = panel.indexOf('const resourceImageFileInput')
  assert.ok(selectFnStart >= 0 && selectFnEnd > selectFnStart)
  const selectFn = panel.slice(selectFnStart, selectFnEnd)
  assert.match(selectFn, /props\.onSelectEpisode\(\)/)
  assert.match(selectFn, /emit\('select-episode'\)/)
  assert.doesNotMatch(selectFn, /activateExistingControl/)
  assert.doesNotMatch(selectFn, /querySelector/)
  assert.doesNotMatch(selectFn, /getElementById/)
  assert.doesNotMatch(selectFn, /header-episode-select/)
  assert.doesNotMatch(panel, /activateExistingControl/)
  assert.doesNotMatch(panel, /header-episode-select/)
  assert.doesNotMatch(panel, /<div v-if="characters\.length === 0" class="empty-tip">暂无角色/)
})

test('资源面板含空状态后仍可编译', () => {
  const parsed = parse(panel, { filename: 'FilmCreateResourcePanel.vue' })
  assert.deepEqual(parsed.errors.map((error) => String(error)), [])
  assert.doesNotThrow(() => compileScript(parsed.descriptor, { id: 'resource-empty-state' }))
})
